import { useEffect } from "react";
import { motion } from "framer-motion";

// The astronomer's private notebook: how each instrument actually works.
// Written for engineers — every note is a real technique from the source.

const NOTES = [
  {
    title: "The prime directive: $0, forever",
    body: (
      <>
        The Observatory has no backend, no database, no AI API, and no analytics.
        Everything runs in your browser against GitHub's free API, cached in
        localStorage. Every "we need a server for this" turned out to be a design
        problem in disguise — the notes below are what that constraint produced.
      </>
    ),
  },
  {
    title: "Star history without a star-history API",
    body: (
      <>
        GitHub has no endpoint for "stars over time." But the stargazers list,
        requested with the <code>application/vnd.github.star+json</code> media
        type, carries a <code>starred_at</code> timestamp — and it's paginated in
        order. So the first stargazer on page 25 is, by definition, star #2,400.
        The Spectrograph samples six pages spread across the range and gets the
        whole cumulative growth curve for six requests. Pagination caps at star
        #40,000; past that, the curve bridges to today's total and says so.
      </>
    ),
  },
  {
    title: "The 'AI' search is a parser, not a model",
    body: (
      <>
        Ask the Sky compiles English straight to GitHub search qualifiers:
        "rust cli tools &gt;1k stars this year" becomes{" "}
        <code>cli tools language:"Rust" stars:&gt;=1000 created:&gt;…</code>.
        Language aliases (js, golang, c#), star ranges (5k+, between X and Y),
        time windows (march 2023, since 2022, past 30 days), activity, and sort
        hints are all regex passes that consume the text; whatever's left becomes
        keywords. Zero latency, zero cost, and the "understood as" chips show
        exactly how it read you — transparency instead of magic.
      </>
    ),
  },
  {
    title: "Supernova math is real astronomy",
    body: (
      <>
        A supernova is a star suddenly far brighter than its baseline. Here:
        stars gained tonight ÷ lifetime stars-per-day average. The Δ-magnitude
        uses the actual astronomical brightness formula, Δm = 2.5·log₁₀(ratio),
        and designations follow supernova convention — SN, date, letter by rank.
        Anything under 3× is filtered out as an ordinary bright day.
      </>
    ),
  },
  {
    title: "Deep Field: signal before luminosity",
    body: (
      <>
        One search over repos younger than 90 days with 40–400 stars, then
        client-side scoring: fork/star ratio weighted 6× (people building on it,
        not admiring it), push freshness, and issue traffic. No description,
        fewer than 3 forks, or 21 days dormant — dropped. The trending page will
        never show you these; that's the point.
      </>
    ),
  },
  {
    title: "Trending has no API, so we read the page",
    body: (
      <>
        github.com/trending is HTML-only and blocks browser CORS. A rewrite
        proxies <code>/gh-trending</code> to it (Vite dev server locally, a
        Vercel rewrite in production), and a DOMParser pass extracts rank, repo,
        stars gained. The Sky Chart, Supernova Watch, Planetarium, and Observer's
        Log all share that single cached fetch.
      </>
    ),
  },
  {
    title: "Rate limits as weather",
    body: (
      <>
        Anonymous visitors get 10 search requests/minute from GitHub, so every
        query is cached in localStorage — and past months never change, so
        archive queries cache <em>forever</em>. When the limit bites, the sky
        reports "cloudy" and serves stale data if it has any. Bring your own
        token (⚙, no scopes needed, stored only in your browser) and the limits
        rise 3×–80×. This Night in History even resumes its sweep where the
        clouds rolled in.
      </>
    ),
  },
  {
    title: "The Observer's Log writes itself, without AI",
    body: (
      <>
        The nightly journal entry is composed from the trending data already in
        cache: champion, runner-up, total sky brightening, a language census.
        Openers and closers are picked from small pools seeded by the date, so
        each night reads differently — deterministically. Generated by nothing.
      </>
    ),
  },
  {
    title: "The Planetarium is one camera",
    body: (
      <>
        A single eased camera {"{x, y, zoom}"} drives everything at 60fps. Each
        star's depth comes from its total mass — log-scaled, so ancient giants
        sit far (smaller, dimmer, blurred) and tonight's risers float close,
        which is why panning parallaxes. The tour is just scripted camera
        targets; your first scroll or drag cancels it and hands you the wheel.
      </>
    ),
  },
];

export default function FieldNotes({ onClose }) {
  useEffect(() => {
    const onKey = (e) => e.key === "Escape" && onClose();
    window.addEventListener("keydown", onKey);
    const prev = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    return () => {
      window.removeEventListener("keydown", onKey);
      document.body.style.overflow = prev;
    };
  }, [onClose]);

  return (
    <div className="fieldnotes" role="dialog" aria-label="Field notes">
      <div className="plan-head">
        <span className="plan-title">✎ Field Notes — how the instrument works</span>
        <button className="plan-close" onClick={onClose}>✕ close</button>
      </div>

      <div className="fn-scroll">
        <div className="fn-inner">
        <p className="fn-intro">
          Notes from the workbench, for engineers who ask "wait, how?" —
          every instrument here runs on a trick worth stealing.
        </p>

        {NOTES.map((n, i) => (
          <motion.article
            key={n.title}
            className="fn-note"
            initial={{ opacity: 0, y: 18 }}
            whileInView={{ opacity: 1, y: 0 }}
            viewport={{ once: true, margin: "-40px" }}
            transition={{ duration: 0.5, delay: 0.05 * Math.min(i, 3) }}
          >
            <span className="fn-num">{String(i + 1).padStart(2, "0")}</span>
            <h3 className="fn-title">{n.title}</h3>
            <p className="fn-body">{n.body}</p>
          </motion.article>
        ))}

        <p className="fn-outro">
          The rest is in the source — the code is the real documentation. ✦
        </p>
        </div>
      </div>
    </div>
  );
}
